package com.spring.job_tracker.ai.models.estatuses;

public enum ESinkEventStatuses {
    JOB_AND_DOCUMENT_ANALYSIS_COMPLETE,
    JOB_AND_DOCUMENT_ANALYSIS_ERROR,
    JOB_NOTES_ANALYSIS_COMPLETE,
    JOB_NOTES_ANALYSIS_ERROR,
    JOB_PRE_INTERVIEW_ANALYSIS_COMPLETE,
    JOB_PRE_INTERVIEW_ANALYSIS_ERROR,
    JOB_POST_INTERVIEW_ANALYSIS_COMPLETE,
    JOB_POST_INTERVIEW_ANALYSIS_ERROR,
    JOB_INTERVIEW_PATTERN_ANALYSIS_COMPLETE,
    JOB_INTERVIEW_PATTERN_ANALYSIS_ERROR,
}
